services:
  dispatch-service:
    build: ./dispatch-service
    container_name: dispatch-service
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  request-sidecar:
    build: ./request-sidecar
    container_name: request-sidecar
    ports:
      - "4003:4000"

  request-service-1:
    build: ./request-service
    depends_on:
      - redis

  request-service-2:
    build: ./request-service
    depends_on:
      - redis

  caddy:
    build: ./caddy
    ports:
      - "8080:80"
    depends_on:
      - request-service-1
      - request-service-2

  redis:
    image: redis:7
