global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "request-service-1"
    metrics_path: /metrics
    static_configs:
      - targets: ["request-service-1:3000"]

  - job_name: "request-service-2"
    metrics_path: /metrics
    static_configs:
      - targets: ["request-service-2:3000"]

  - job_name: "dispatch-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["dispatch-service:3001"]

  - job_name: "request-sidecar"
    metrics_path: /metrics
    static_configs:
      - targets: ["request-sidecar:4000"]

  - job_name: "async-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["async-worker:3000"]
