global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "request-service-1"
    metrics_path: /metrics
    static_configs:
      - targets: ["request-service-1:3000"]

  - job_name: "request-service-2"
    metrics_path: /metrics
    static_configs:
      - targets: ["request-service-2:3000"]
